name = "NRES"
uuid = "0386fec6-9a84-41c6-97a4-e93b828af035"
authors = ["Per RL <leikange@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1"
